name: lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

defaults:
  run:
    shell: nu {0}

jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - uses: actions/checkout@v4.0.0
        with:
          sparse-checkout: .
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check **/*.{ts,md,yml}
