name: lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

defaults:
  run:
    shell: nu {0}

jobs:
  format-ts-and-elm:
    runs-on: ubuntu-latest
    steps:
      - uses: hustcer/setup-nu@v3.6
        with:
          version: "0.85.0"
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: npm install
        run: npm install
      - name: check format with prettier
        run: npm run prettier-check
      - name: check elm-format
        run: npm run elm-format-check
