name: lint

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

defaults:
  run:
    shell: nu {0}

jobs:
  ts-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: hustcer/setup-nu@main
        with:
          version: "*"
      - uses: actions/checkout@v4.0.0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - name: npm install
        run: npm install
      - name: check format with prettier
        run: npm run prettier-check
